// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Infrastructure.Data;

#nullable disable

namespace SchoolManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20241105044046_InitalMigration2")]
    partial class InitalMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2005, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTown = "HomeTown1",
                            Name = "Student1"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2003, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTown = "HomeTown2",
                            Name = "Student2"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2005, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTown = "HomeTown3",
                            Name = "Student3"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2004, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTown = "HomeTown4",
                            Name = "Student4"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2003, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTown = "HomeTown0",
                            Name = "Student5"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2005, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTown = "HomeTown1",
                            Name = "Student6"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2003, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTown = "HomeTown2",
                            Name = "Student7"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2003, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTown = "HomeTown3",
                            Name = "Student8"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2003, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTown = "HomeTown4",
                            Name = "Student9"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2005, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTown = "HomeTown0",
                            Name = "Student10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
