// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Infrastructure.Data;

#nullable disable

namespace SchoolManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20241105045020_InitialMigration3")]
    partial class InitialMigration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2003, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emailStudent1@gmail.com",
                            HomeTown = "HomeTown1",
                            Name = "Student1"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2004, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emailStudent2@gmail.com",
                            HomeTown = "HomeTown2",
                            Name = "Student2"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2005, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emailStudent3@gmail.com",
                            HomeTown = "HomeTown3",
                            Name = "Student3"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2004, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emailStudent4@gmail.com",
                            HomeTown = "HomeTown4",
                            Name = "Student4"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2004, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emailStudent5@gmail.com",
                            HomeTown = "HomeTown0",
                            Name = "Student5"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2005, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emailStudent6@gmail.com",
                            HomeTown = "HomeTown1",
                            Name = "Student6"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2002, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emailStudent7@gmail.com",
                            HomeTown = "HomeTown2",
                            Name = "Student7"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2005, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emailStudent8@gmail.com",
                            HomeTown = "HomeTown3",
                            Name = "Student8"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2002, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emailStudent9@gmail.com",
                            HomeTown = "HomeTown4",
                            Name = "Student9"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2004, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emailStudent10@gmail.com",
                            HomeTown = "HomeTown0",
                            Name = "Student10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
